<script lang="ts">
	import { Accordion, Popover, SegmentedControl } from '@skeletonlabs/skeleton-svelte';
	import { init } from '@paralleldrive/cuid2';
	import {
		RefreshOutline,
		WandMagicSparklesOutline,
		DotsHorizontalOutline
	} from 'flowbite-svelte-icons';
	import {
		AllAirportsStore,
		AllAirspacesStore,
		AwaitingServerResponseStore,
		HasEmergenciesStore,
		maxFlightLevelStore,
		PlannerUnnamedWaypointCountStore,
		RouteDistanceDisplayUnitStore,
		ScenarioSeedStore,
		WaypointsStore
	} from '$lib/stores';
	import { resolve } from '$app/paths';
	import type Waypoint from '$lib/logic/aeronautics/Waypoint';
	import { WaypointType } from '$lib/logic/aeronautics/Waypoint';
	import { flip } from 'svelte/animate';
	import { loadRouteData } from '$lib/logic/scenarioRoute';
	import { generateFRTOLRouteFromSeed } from '$lib/logic/RouteGeneration';
	import { SvelteSet } from 'svelte/reactivity';
	import { get } from 'svelte/store';
	import FixWaypointMarkerIcon, {
		isRouteEndpoint
	} from '$lib/components/leaflet/FixWaypointMarkerIcon.svelte';
	import AirportMarkerIcon, {
		runwaysToSymbolInput
	} from '$lib/components/leaflet/AirportMarkerIcon.svelte';
	import type Airport from '$lib/logic/aeronautics/Airport';
	import { dialog } from '$lib/components/singletons/dialog.svelte';
	import {
		applyPlannerState,
		clearPlannerPersistedState,
		collectPlannerState,
		getDefaultPlannerState,
		initializePlannerFromStorage,
		isPlannerPersistenceEnabled,
		reenablePlannerPersistenceAfterReset,
		savePlannerPersistedState
	} from '$lib/persistence/localStorageState';

	const SIDEBAR_WAYPOINT_ICON_SIZE = 20;

	function getAirportForWaypoint(waypoint: Waypoint): Airport | undefined {
		if (!waypoint.referenceObjectId) return undefined;
		return get(AllAirportsStore).find((airport) => airport.id === waypoint.referenceObjectId);
	}

	const shortCUID = init({ length: 8 });

	const savedPlannerState = initializePlannerFromStorage(shortCUID());
	const restoredRouteSeed = savedPlannerState?.routeSeed ?? '';

	let routeSeed = $state(restoredRouteSeed);
	// Match restored seed so auto-generate does not replace saved waypoints on first load.
	let lastAutoGeneratedRouteSeed = $state(restoredRouteSeed);

	async function loadSeededRoute(seed: string) {
		AwaitingServerResponseStore.set(true);
		const routeData = await generateFRTOLRouteFromSeed(
			seed,
			get(AllAirportsStore),
			get(AllAirspacesStore),
			get(maxFlightLevelStore)
		);
		if (routeData) {
			loadRouteData(routeData, { clearSimulation: false });
		}
		AwaitingServerResponseStore.set(false);
	}

	$effect(() => {
		if (routeSeed === '' || routeSeed === lastAutoGeneratedRouteSeed) return;
		if (get(AwaitingServerResponseStore)) return;

		lastAutoGeneratedRouteSeed = routeSeed;
		loadSeededRoute(routeSeed);
	});

	$effect(() => {
		const fl = get(maxFlightLevelStore);
		if (fl < 15) {
			maxFlightLevelStore.set(15);
		}
	});

	const dragDuration = 200;
	let draggingWaypoint = $state<Waypoint | undefined>(undefined);
	const animatingWaypoints = new SvelteSet<Waypoint>();

	function swapWith(waypoint: Waypoint): void {
		const dragging = draggingWaypoint;
		if (!dragging || !waypoint) return;
		if (dragging === waypoint || animatingWaypoints.has(waypoint)) return;

		animatingWaypoints.add(waypoint);
		setTimeout(() => animatingWaypoints.delete(waypoint), dragDuration);

		const waypoints = get(WaypointsStore);
		const cardAIndex = waypoints.indexOf(dragging);
		const cardBIndex = waypoints.indexOf(waypoint);
		if (cardAIndex < 0 || cardBIndex < 0) return;

		const reordered = [...waypoints];
		reordered[cardAIndex] = waypoint;
		reordered[cardBIndex] = dragging;
		reordered.forEach((wp, index) => {
			wp.index = index;
		});
		WaypointsStore.set(reordered);
	}

	function deleteWaypoint(id: string): void {
		WaypointsStore.update((waypoints) => {
			const filtered = waypoints.filter((w) => w.id !== id);
			filtered.forEach((wp, index) => {
				wp.index = index;
			});
			return filtered;
		});
	}

	$effect(() => {
		if (!isPlannerPersistenceEnabled()) return;

		savePlannerPersistedState(
			collectPlannerState({
				routeSeed,
				unnamedWaypointCount: $PlannerUnnamedWaypointCountStore
			})
		);
	});

	function resetPlanner(): void {
		dialog.trigger({
			type: 'confirm',
			title: 'Reset plan?',
			body: 'This will clear your saved route and planner settings from this browser. This cannot be undone.',
			response: (confirmed) => {
				if (!confirmed) return;

				clearPlannerPersistedState();
				const defaults = getDefaultPlannerState(shortCUID());
				applyPlannerState(defaults);
				reenablePlannerPersistenceAfterReset();
				PlannerUnnamedWaypointCountStore.set(defaults.unnamedWaypointCount);
				routeSeed = defaults.routeSeed;
				lastAutoGeneratedRouteSeed = defaults.routeSeed;
			}
		});
	}
</script>

<div
	class="sidebar-container grid h-full min-h-0 w-full grid-rows-[auto_minmax(0,1fr)_minmax(0,40%)_auto] overflow-hidden py-0"
>
	<div class="flex shrink-0 flex-col bg-surface-100 p-3 dark:bg-surface-900">
		<strong><a href={resolve('/')} class="btn text-xl uppercase sm:text-2xl">RT Trainer</a></strong>

		<ol class="flex flex-row gap-2 pb-2 pl-3.5 font-light">
			<li class="">Scenario Planner</li>
		</ol>

		<hr />
	</div>

	<section class="min-h-0 overflow-y-auto overscroll-contain px-3">
		<div class="flex flex-col gap-2 px-2 pb-2">
			<div><strong>Route Waypoints</strong></div>
			{#if $WaypointsStore.length == 0}
				<div class="px-1">
					<p class="text-sm text-slate-600 dark:text-slate-400">
						Add a waypoint by clicking on an airport or any other spot on the map. Or use the <b
							>Auto-generate</b
						> Tool below.
					</p>
				</div>
			{/if}
			{#each $WaypointsStore as waypoint, index (waypoint.id)}
				<!-- svelte-ignore a11y_no_static_element_interactions -->
				<div
					class="flex flex-row place-content-center gap-2 card p-2"
					draggable="true"
					animate:flip={{ duration: dragDuration }}
					ondragstart={() => {
						draggingWaypoint = waypoint;
					}}
					ondragend={() => {
						draggingWaypoint = undefined;
					}}
					ondragenter={() => {
						swapWith(waypoint);
					}}
					ondragover={(e) => {
						e.preventDefault();
					}}
				>
					<div class="flex flex-col place-content-center">
						{#if waypoint.type == WaypointType.Airport}
							<AirportMarkerIcon
								size={SIDEBAR_WAYPOINT_ICON_SIZE}
								runways={runwaysToSymbolInput(getAirportForWaypoint(waypoint)?.runways)}
								showRouteEndpoint={isRouteEndpoint(index, $WaypointsStore.length)}
							/>
						{:else}
							<FixWaypointMarkerIcon
								size={SIDEBAR_WAYPOINT_ICON_SIZE}
								showRouteEndpoint={isRouteEndpoint(index, $WaypointsStore.length)}
							/>
						{/if}
					</div>
					<div class="flex flex-col place-content-center">
						<textarea class="textarea" rows="1" placeholder={waypoint.name}></textarea>
					</div>
					<Popover>
						<Popover.Trigger class="flex flex-col place-content-center">
							<DotsHorizontalOutline />
						</Popover.Trigger>
						<Popover.Positioner>
							<Popover.Content class="z-50 w-auto card p-4 shadow-xl">
								<button onclick={() => deleteWaypoint(waypoint.id)}>Delete</button>
							</Popover.Content>
						</Popover.Positioner>
					</Popover>
				</div>
			{/each}
		</div>
	</section>

	<div class="min-h-0 overflow-y-auto overscroll-contain px-3 pb-2">
		<div class="flex flex-col gap-2 p-2">
			<div>
				<strong>Scenario Settings</strong>
			</div>
			<div class="flex flex-col gap-1">
				<div class="label text-sm">Scenario Seed</div>
				<div class="flex flex-row gap-2">
					<textarea
						id="scenario-seed-input"
						class="textarea"
						rows="1"
						maxlength="20"
						placeholder="Enter a seed"
						bind:value={$ScenarioSeedStore}
					></textarea>
					<button
						type="button"
						class="btn w-10 preset-filled"
						disabled={$AwaitingServerResponseStore}
						onclick={() => {
							$ScenarioSeedStore = shortCUID();
						}}><RefreshOutline /></button
					>
				</div>
			</div>

			<label class="flex items-center space-x-2">
				<input
					id="emergency-events-checkbox"
					class="checkbox"
					type="checkbox"
					bind:checked={$HasEmergenciesStore}
				/>
				<p>Emergency Events</p>
			</label>
		</div>

		<div class="flex flex-col gap-2 p-2">
			<div>
				<strong>Preferences</strong>
			</div>
			<div>
				<div class="flex flex-col gap-1">
					<SegmentedControl
						value={$RouteDistanceDisplayUnitStore}
						onValueChange={(details) => {
							if (details.value) {
								$RouteDistanceDisplayUnitStore = details.value;
							}
						}}
					>
						<SegmentedControl.Label class="text-sm">Distance Units</SegmentedControl.Label>
						<SegmentedControl.Control>
							<SegmentedControl.Indicator />
							<SegmentedControl.Item value="Nautical Miles">
								<SegmentedControl.ItemText>nm</SegmentedControl.ItemText>
								<SegmentedControl.ItemHiddenInput />
							</SegmentedControl.Item>
							<SegmentedControl.Item value="Miles">
								<SegmentedControl.ItemText>mi</SegmentedControl.ItemText>
								<SegmentedControl.ItemHiddenInput />
							</SegmentedControl.Item>
							<SegmentedControl.Item value="Kilometers">
								<SegmentedControl.ItemText>km</SegmentedControl.ItemText>
								<SegmentedControl.ItemHiddenInput />
							</SegmentedControl.Item>
						</SegmentedControl.Control>
					</SegmentedControl>
				</div>
			</div>

			<div class="flex flex-col gap-1">
				<div class="label text-sm">Maximum Flight Level (100 ft)</div>
				<textarea
					id="fl-input"
					class="textarea"
					rows="1"
					maxlength="4"
					bind:value={$maxFlightLevelStore}
				></textarea>
			</div>
		</div>

		<div class="flex flex-col gap-2 p-2">
			<div>
				<strong>Tools</strong>
			</div>

			<Accordion multiple>
				<Accordion.Item value="auto-generate-route">
					<h3>
						<Accordion.ItemTrigger class="flex items-center justify-between gap-2 font-bold">
							Auto-generate Route
							<Accordion.ItemIndicator class="group">
								<WandMagicSparklesOutline />
							</Accordion.ItemIndicator>
						</Accordion.ItemTrigger>
					</h3>
					<Accordion.ItemContent>
						<div class="flex flex-col gap-2">
							<div class="label">Route Seed</div>
							<div class="flex flex-row gap-2">
								<textarea
									id="route-seed-input"
									class="textarea"
									rows="1"
									maxlength="20"
									placeholder="Enter a seed"
									bind:value={routeSeed}
								></textarea>
								<button
									type="button"
									class="btn w-10 preset-filled"
									disabled={$AwaitingServerResponseStore}
									onclick={() => {
										routeSeed = shortCUID();
									}}><RefreshOutline /></button
								>
							</div>
						</div>
					</Accordion.ItemContent>
				</Accordion.Item>
			</Accordion>
		</div>
	</div>

	<div class="shrink-0 border-t border-surface-200 px-3 py-3 dark:border-surface-700">
		<button type="button" class="btn w-full preset-tonal-error text-sm" onclick={resetPlanner}>
			Reset plan
		</button>
	</div>
</div>

<style>
	textarea {
		resize: none;
	}
</style>
